### ISSUE TITLE
Enabling secure boot HAB?

### ISSUE THREAD

**Issue by mvargasevans** [compulab-yokneam/meta-bsp-imx7#2]
Hi everyone,

First, thanks for the work on this branch. Really appreciate it!

I am interested in testing the secure boot options using HAB  [here](https://mediawiki.compulab.com/w/index.php?title=IOT-GATE-iMX7_and_SBC-IOT-iMX7:_U-Boot:_Building_Secure_Images).

I found that parts of the UBoot code are including CONFIG_SECURE_BOOT, which is necessary for this.
At this point, I just would like to ask if this has been tested and any pointers to what would be needed.

Thanks!

**Comment by vraevsky** [comment]
Hi,

The HAB man page at the CompuLab Web Site covers steps of signing the U-Boot ant the Kernel.
As of now all that needed are included. Unfortunately, the entire HAB procedure was not tested on the latest U-Boot.

BR,
Val.
