### ISSUE TITLE
missing conf/machine/*.conf files in master branch

### ISSUE THREAD

**Issue by codysch** [compulab-yokneam/meta-bsp-imx7#3]
Based on the readme, `conf/machine/cl-som-imx7.conf` should exist, but it doesn't appear in `master`, only in `devel-warrior` (which is noted as not an official release).

Should the `cl-som-imx7.conf` from `devel-warrior` be placed into `master`? Or is there some other machine definition that should be used?

**Comment by vraevsky** [comment]
Dear Cody,

1) Thanks for being interested in  a CompuLab product.
2) About 'conf/machine/cl-som-imx7.conf' file:
master - includes the machine file from another layer 'meta-compulab'
devel-warrior - has its own machine file.

BR,
Val.
