### ISSUE TITLE
ca-certificates-20170717-r0

### ISSUE THREAD

**Issue by vaib09** [compulab-yokneam/meta-bsp-imx7#4]
After following all the steps mentioned, I am getting this error (ERROR: ca-certificates-20170717-r0 do_compile: oe_runmake failed) while trying to do bitbake -k core-image-minimal. I have attached the log. Any suggestion would be apperciated.
[log_1.odt](https://github.com/compulab-yokneam/meta-bsp-imx7/files/6781889/log_1.odt)

**Comment by vraevsky** [comment]
Here are two options:
1) This is a mozila certification issue. Remove it from the build or turn to the mozila maintainers.
2) Try this branch: https://github.com/compulab-yokneam/meta-bsp-imx7/tree/gatesgarth.

**Comment by vaib09** [comment]
Thanks @vraevsky . I have tried 2nd option and it works perfectly.
