### ISSUE TITLE
__sync_val_compare_and_swap_4 Undefined

### ISSUE THREAD

**Issue by vaib09** [compulab-yokneam/meta-bsp-imx7#5]
I am sorry if it's a wrong platform to ask this question. I am trying to build kernel drivers for my project and facing this error  ERROR: modpost: "__sync_val_compare_and_swap_4" [   ] Undefined! 

BSP - meta-bsp-imx7 branch gatesgarth

Any suggestion would be appreciated.

**Comment by vraevsky** [comment]
Please provide:
1) the entire build log that shows the issue;
2) the compiler version.
3) information of the changes made in the CompuLab imx7 kernel code.

**Comment by vaib09** [comment]
[error_log_1.odt](https://github.com/compulab-yokneam/meta-bsp-imx7/files/6964526/error_log_1.odt)
Kernel version 5.10.9
GCC compiler 10.2.
Haven't made any changes  in the CompuLab imx7 kernel code. Build the core-image-minimal.

**Comment by vraevsky** [comment]
Please compress and post ${BUILDDIR}/conf folder.

**Comment by vaib09** [comment]
[conf.zip](https://github.com/compulab-yokneam/meta-bsp-imx7/files/6969065/conf.zip)
meta-mylayer 
[conf_build.zip](https://github.com/compulab-yokneam/meta-bsp-imx7/files/6969094/conf_build.zip)
build environment conf

**Comment by vraevsky** [comment]
@vaib09 thanks for providing the confs.
Please remove the `BBLAYERS += "/home/vaibhav/compulab-bsp/sources/meta-cloakd"` line from the conf/bblayer.conf
This is not a CompuLab provided layer.

**Comment by vaib09** [comment]
@vraevsky This is the meta layer where i have kept my customized kernel modules.

**Comment by vaib09** [comment]
I think this error is because of incompatibility between two object files linked together. Since my code base is based on U32 and arm-poky-linux-gnueabi-gcc is U16. Is their any way i can up rebuild yocto image to U32.

**Comment by vraevsky** [comment]
All objects must be compiled by the same toolchain. Apply the base changes to the meta-cloakd source.
